export const FETCH_ALL = 'FETCH_ALL';
export const INSERT = 'INSERT';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const LOGINERROR = 'LOGINERROR';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const REGERROR = 'REGERROR';
export const REGSUCCESS = 'REGSUCCESS';

export const AUTHADMIN = 'AUTHADMIN';

export const REFRESHAUTH = 'REFRESHAUTH';

export const LOGOUT = 'LOGOUT';
export const SUCCESSLOGIN = 'SUCCESS';
export const AUTHERROR = 'AUTHERROR';
export const VALIDATE_INPUT_ERROR = 'VALIDATE_INPUT_ERROR';



//STAFF
export const ADDSTAFF = 'ADDSTAFF';
export const EDITSTAFF = 'EDITSTAFF';
export const DELETESTAFF = 'DELETESTAFF';
export const GETSTAFF = 'GETSTAFF';

//STUDENT
export const GETCOURSE = 'GETCOURSE';
export const GETSTUDENTS = 'GETSTUDENTS';
export const SUCCESSINSERTSTUDENT = 'SUCCESSINSERTSTUDENT';
export const ERRORINSERTSTUDENT = 'ERRORINSERTSTUDENT';
export const SUCCESSUPDATESTUDENT = 'SUCCESSUPDATESTUDENT';
export const DELETESTUDENT = 'DELETESTUDENT';
